import type { ToolType } from '../types/diagram'

export const HOTKEYS: Record<string, ToolType | string> = {
  'v': 'select-click',
  'b': 'select-box',
  'l': 'select-lasso',
  'p': 'pan',
  'r': 'rectangle',
  'c': 'circle',
  'o': 'line',
  'a': 'arrow',
  'delete': 'delete',
  'backspace': 'delete',
  'escape': 'deselect',
}

export const HOTKEY_LABELS: Record<string, string> = {
  'v': 'Select (Click)',
  'b': 'Select (Box)',
  'l': 'Select (Lasso)',
  'r': 'Rectangle',
  'c': 'Circle',
  'o': 'Line',
  'a': 'Arrow',
  'delete': 'Delete',
  'backspace': 'Delete',
  'escape': 'Deselect',
  '?': 'Show Help',
}

export const ALL_HOTKEYS = [
  { key: 'V', action: 'select-click', description: 'Click to select shapes' },
  { key: 'B', action: 'select-box', description: 'Draw a box to select shapes' },
  { key: 'L', action: 'select-lasso', description: 'Draw a lasso to select shapes' },
  { key: 'P', action: 'pan', description: 'Pan the canvas' },
  { key: 'R', action: 'rectangle', description: 'Draw rectangles' },
  { key: 'C', action: 'circle', description: 'Draw circles' },
  { key: 'O', action: 'line', description: 'Draw lines' },
  { key: 'A', action: 'arrow', description: 'Draw arrows' },
  { key: 'Delete / Backspace', action: 'delete', description: 'Delete selected shapes' },
  { key: 'Escape', action: 'deselect', description: 'Deselect all shapes' },
  { key: 'Space + Drag', action: 'pan-drag', description: 'Pan with space held' },
  { key: 'Ctrl/Cmd + Wheel', action: 'zoom', description: 'Zoom in/out' },
  { key: 'Ctrl/Cmd + Z', action: 'undo', description: 'Undo' },
  { key: 'Ctrl/Cmd + Shift + Z', action: 'redo', description: 'Redo' },
  { key: 'Ctrl/Cmd + Y', action: 'redo', description: 'Redo' },
  { key: 'Ctrl+Alt+L', action: 'align-left', description: 'Align left' },
  { key: 'Ctrl+Alt+C', action: 'align-center', description: 'Align center' },
  { key: 'Ctrl+Alt+R', action: 'align-right', description: 'Align right' },
  { key: 'Ctrl+Alt+T', action: 'align-top', description: 'Align top' },
  { key: 'Ctrl+Alt+M', action: 'align-middle', description: 'Align middle' },
  { key: 'Ctrl+Alt+B', action: 'align-bottom', description: 'Align bottom' },
  { key: 'Ctrl+Alt+Shift+H', action: 'distribute-horizontal', description: 'Distribute horizontally' },
  { key: 'Ctrl+Alt+Shift+V', action: 'distribute-vertical', description: 'Distribute vertically' },
  { key: '?', action: 'help', description: 'Show keyboard shortcuts' },
]
